### ISSUE TITLE
App is crashing in some devices when I run this command.

### ISSUE THREAD

**Issue by RahulChokshiDev** [elich11/ffmpeg4android#3]
**I don't why app is crashing some android devices when I run this command** 

**Command:-**

ffmpeg -loop 1 -i demo.png -i demoVideo.mp4 -filter_complex \
"[1]trim=end_frame=1,geq='st(3,pow(X-(W/2),2)+pow(Y-(H/2),2));if(lte(ld(3),pow(min(W/2,H/2),2)),255,0)':128:128,loop=-1:1,setpts=N/FRAME_RATE/TB[mask];[1][mask]alphamerge[cutout];[cutout]scale=400:400[cir];[0][cir]overlay=x=(" + (((width * (xPosition - ivCroppedImage.getX())) / ivCroppedImage.getWidth())) + "):y=(" + ((((width * (yPosition - ivCroppedImage.getY())) / ivCroppedImage.getWidth()))) + "):shortest=1[out] -map [out] -map 1:a -preset ultrafast -filter_complex_threads 1 -c:a copy -y  out.mp4

**Vk.Log**

ffmpeg version git-2016-10-26-efa89a8 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9 (GCC) 20140827 (prerelease)
ffmpeg4android 3.22_03_full_p28_LM41 
  libavutil      55. 35.100 / 55. 35.100
  libavcodec     57. 65.100 / 57. 65.100
  libavformat    57. 57.100 / 57. 57.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 66.100 /  6. 66.100
  libswscale      4.  3.100 /  4.  3.100
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Splitting the commandline.
Reading option '-loop' ... matched as AVOption 'loop' with argument '1'.
Reading option '-i' ... matched as input file with argument '/storage/emulated/0/.YadayadaTemp/YadaYadaImageCropTemp/cropped_201910111346.jpg'.
Reading option '-i' ... matched as input file with argument '/storage/emulated/0/.YadaYadaTemp/YadaYadaRecordingTemp/extract_picture_201910111346.mp4'.
Reading option '-filter_complex' ... matched as option 'filter_complex' (create a complex filtergraph) with argument '[1]trim=end_frame=1,geq='st(3,pow(X-(W/2),2)+pow(Y-(H/2),2));if(lte(ld(3),pow(min(W/2,H/2),2)),255,0)':128:128,loop=-1:1,setpts=N/FRAME_RATE/TB[mask];[1][mask]alphamerge[cutout];[cutout]scale=210.0:210.0[cir];[0][cir]overlay=x=(524.0):y=(244.0):shortest=1[out]'.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '[out]'.
Reading option '-map' ... matched as option 'map' (set input stream mapping) with argument '1:a'.
Reading option '-preset' ... matched as AVOption 'preset' with argument 'ultrafast'.
Reading option '-filter_complex_threads' ...Unrecognized option 'filter_complex_threads'.
Error splitting the argument list: Option not found
ffmpeg4android: ffmpeg_parse_options not passed

**Comment by elich11** [comment]
32bit device that does not support this command.
